### ISSUE TITLE
[computer-use-demo] Error pulling and running image

### ISSUE THREAD

**Issue by anishhiranandani** [anthropics/claude-quickstarts#47]
Cloned repository successfully
However, getting this error when I try to build/run the container:

Error: initializing source docker://ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest: pinging container registry ghcr.io: Get "https://ghcr.io/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by x5a** [comment]
Hi @anishhiranandani see [this discussion](https://github.com/orgs/community/discussions/26917) for more details:
- the certificates on your system are out of date
- there is some other firewall or network issue blocking the TLS handshake.

You can follow the development instructions to build the image locally rather than using the prebuilt images in the github container repository
